// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.27.2

package grpc;

/**
 * Protobuf type {@code grpc.GameManagementGetAllResponse}
 */
public final class GameManagementGetAllResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:grpc.GameManagementGetAllResponse)
    GameManagementGetAllResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      GameManagementGetAllResponse.class.getName());
  }
  // Use GameManagementGetAllResponse.newBuilder() to construct.
  private GameManagementGetAllResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GameManagementGetAllResponse() {
    games_ = java.util.Collections.emptyList();
    message_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.Service.internal_static_grpc_GameManagementGetAllResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.Service.internal_static_grpc_GameManagementGetAllResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.GameManagementGetAllResponse.class, grpc.GameManagementGetAllResponse.Builder.class);
  }

  public static final int GAMES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<grpc.GameManagementGetResponse> games_;
  /**
   * <code>repeated .grpc.GameManagementGetResponse games = 1;</code>
   */
  @java.lang.Override
  public java.util.List<grpc.GameManagementGetResponse> getGamesList() {
    return games_;
  }
  /**
   * <code>repeated .grpc.GameManagementGetResponse games = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends grpc.GameManagementGetResponseOrBuilder> 
      getGamesOrBuilderList() {
    return games_;
  }
  /**
   * <code>repeated .grpc.GameManagementGetResponse games = 1;</code>
   */
  @java.lang.Override
  public int getGamesCount() {
    return games_.size();
  }
  /**
   * <code>repeated .grpc.GameManagementGetResponse games = 1;</code>
   */
  @java.lang.Override
  public grpc.GameManagementGetResponse getGames(int index) {
    return games_.get(index);
  }
  /**
   * <code>repeated .grpc.GameManagementGetResponse games = 1;</code>
   */
  @java.lang.Override
  public grpc.GameManagementGetResponseOrBuilder getGamesOrBuilder(
      int index) {
    return games_.get(index);
  }

  public static final int FINISHED_FIELD_NUMBER = 2;
  private boolean finished_ = false;
  /**
   * <code>bool finished = 2;</code>
   * @return The finished.
   */
  @java.lang.Override
  public boolean getFinished() {
    return finished_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object message_ = "";
  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < games_.size(); i++) {
      output.writeMessage(1, games_.get(i));
    }
    if (finished_ != false) {
      output.writeBool(2, finished_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, message_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < games_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, games_.get(i));
    }
    if (finished_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, finished_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, message_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.GameManagementGetAllResponse)) {
      return super.equals(obj);
    }
    grpc.GameManagementGetAllResponse other = (grpc.GameManagementGetAllResponse) obj;

    if (!getGamesList()
        .equals(other.getGamesList())) return false;
    if (getFinished()
        != other.getFinished()) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getGamesCount() > 0) {
      hash = (37 * hash) + GAMES_FIELD_NUMBER;
      hash = (53 * hash) + getGamesList().hashCode();
    }
    hash = (37 * hash) + FINISHED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFinished());
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.GameManagementGetAllResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.GameManagementGetAllResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.GameManagementGetAllResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.GameManagementGetAllResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.GameManagementGetAllResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.GameManagementGetAllResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.GameManagementGetAllResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static grpc.GameManagementGetAllResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static grpc.GameManagementGetAllResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static grpc.GameManagementGetAllResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.GameManagementGetAllResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static grpc.GameManagementGetAllResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.GameManagementGetAllResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.GameManagementGetAllResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.GameManagementGetAllResponse)
      grpc.GameManagementGetAllResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.Service.internal_static_grpc_GameManagementGetAllResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.Service.internal_static_grpc_GameManagementGetAllResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.GameManagementGetAllResponse.class, grpc.GameManagementGetAllResponse.Builder.class);
    }

    // Construct using grpc.GameManagementGetAllResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (gamesBuilder_ == null) {
        games_ = java.util.Collections.emptyList();
      } else {
        games_ = null;
        gamesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      finished_ = false;
      message_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.Service.internal_static_grpc_GameManagementGetAllResponse_descriptor;
    }

    @java.lang.Override
    public grpc.GameManagementGetAllResponse getDefaultInstanceForType() {
      return grpc.GameManagementGetAllResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.GameManagementGetAllResponse build() {
      grpc.GameManagementGetAllResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.GameManagementGetAllResponse buildPartial() {
      grpc.GameManagementGetAllResponse result = new grpc.GameManagementGetAllResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(grpc.GameManagementGetAllResponse result) {
      if (gamesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          games_ = java.util.Collections.unmodifiableList(games_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.games_ = games_;
      } else {
        result.games_ = gamesBuilder_.build();
      }
    }

    private void buildPartial0(grpc.GameManagementGetAllResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.finished_ = finished_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.message_ = message_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.GameManagementGetAllResponse) {
        return mergeFrom((grpc.GameManagementGetAllResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.GameManagementGetAllResponse other) {
      if (other == grpc.GameManagementGetAllResponse.getDefaultInstance()) return this;
      if (gamesBuilder_ == null) {
        if (!other.games_.isEmpty()) {
          if (games_.isEmpty()) {
            games_ = other.games_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureGamesIsMutable();
            games_.addAll(other.games_);
          }
          onChanged();
        }
      } else {
        if (!other.games_.isEmpty()) {
          if (gamesBuilder_.isEmpty()) {
            gamesBuilder_.dispose();
            gamesBuilder_ = null;
            games_ = other.games_;
            bitField0_ = (bitField0_ & ~0x00000001);
            gamesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getGamesFieldBuilder() : null;
          } else {
            gamesBuilder_.addAllMessages(other.games_);
          }
        }
      }
      if (other.getFinished() != false) {
        setFinished(other.getFinished());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              grpc.GameManagementGetResponse m =
                  input.readMessage(
                      grpc.GameManagementGetResponse.parser(),
                      extensionRegistry);
              if (gamesBuilder_ == null) {
                ensureGamesIsMutable();
                games_.add(m);
              } else {
                gamesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16: {
              finished_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              message_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<grpc.GameManagementGetResponse> games_ =
      java.util.Collections.emptyList();
    private void ensureGamesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        games_ = new java.util.ArrayList<grpc.GameManagementGetResponse>(games_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        grpc.GameManagementGetResponse, grpc.GameManagementGetResponse.Builder, grpc.GameManagementGetResponseOrBuilder> gamesBuilder_;

    /**
     * <code>repeated .grpc.GameManagementGetResponse games = 1;</code>
     */
    public java.util.List<grpc.GameManagementGetResponse> getGamesList() {
      if (gamesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(games_);
      } else {
        return gamesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .grpc.GameManagementGetResponse games = 1;</code>
     */
    public int getGamesCount() {
      if (gamesBuilder_ == null) {
        return games_.size();
      } else {
        return gamesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .grpc.GameManagementGetResponse games = 1;</code>
     */
    public grpc.GameManagementGetResponse getGames(int index) {
      if (gamesBuilder_ == null) {
        return games_.get(index);
      } else {
        return gamesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .grpc.GameManagementGetResponse games = 1;</code>
     */
    public Builder setGames(
        int index, grpc.GameManagementGetResponse value) {
      if (gamesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGamesIsMutable();
        games_.set(index, value);
        onChanged();
      } else {
        gamesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementGetResponse games = 1;</code>
     */
    public Builder setGames(
        int index, grpc.GameManagementGetResponse.Builder builderForValue) {
      if (gamesBuilder_ == null) {
        ensureGamesIsMutable();
        games_.set(index, builderForValue.build());
        onChanged();
      } else {
        gamesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementGetResponse games = 1;</code>
     */
    public Builder addGames(grpc.GameManagementGetResponse value) {
      if (gamesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGamesIsMutable();
        games_.add(value);
        onChanged();
      } else {
        gamesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementGetResponse games = 1;</code>
     */
    public Builder addGames(
        int index, grpc.GameManagementGetResponse value) {
      if (gamesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGamesIsMutable();
        games_.add(index, value);
        onChanged();
      } else {
        gamesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementGetResponse games = 1;</code>
     */
    public Builder addGames(
        grpc.GameManagementGetResponse.Builder builderForValue) {
      if (gamesBuilder_ == null) {
        ensureGamesIsMutable();
        games_.add(builderForValue.build());
        onChanged();
      } else {
        gamesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementGetResponse games = 1;</code>
     */
    public Builder addGames(
        int index, grpc.GameManagementGetResponse.Builder builderForValue) {
      if (gamesBuilder_ == null) {
        ensureGamesIsMutable();
        games_.add(index, builderForValue.build());
        onChanged();
      } else {
        gamesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementGetResponse games = 1;</code>
     */
    public Builder addAllGames(
        java.lang.Iterable<? extends grpc.GameManagementGetResponse> values) {
      if (gamesBuilder_ == null) {
        ensureGamesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, games_);
        onChanged();
      } else {
        gamesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementGetResponse games = 1;</code>
     */
    public Builder clearGames() {
      if (gamesBuilder_ == null) {
        games_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        gamesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementGetResponse games = 1;</code>
     */
    public Builder removeGames(int index) {
      if (gamesBuilder_ == null) {
        ensureGamesIsMutable();
        games_.remove(index);
        onChanged();
      } else {
        gamesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementGetResponse games = 1;</code>
     */
    public grpc.GameManagementGetResponse.Builder getGamesBuilder(
        int index) {
      return getGamesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .grpc.GameManagementGetResponse games = 1;</code>
     */
    public grpc.GameManagementGetResponseOrBuilder getGamesOrBuilder(
        int index) {
      if (gamesBuilder_ == null) {
        return games_.get(index);  } else {
        return gamesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .grpc.GameManagementGetResponse games = 1;</code>
     */
    public java.util.List<? extends grpc.GameManagementGetResponseOrBuilder> 
         getGamesOrBuilderList() {
      if (gamesBuilder_ != null) {
        return gamesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(games_);
      }
    }
    /**
     * <code>repeated .grpc.GameManagementGetResponse games = 1;</code>
     */
    public grpc.GameManagementGetResponse.Builder addGamesBuilder() {
      return getGamesFieldBuilder().addBuilder(
          grpc.GameManagementGetResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc.GameManagementGetResponse games = 1;</code>
     */
    public grpc.GameManagementGetResponse.Builder addGamesBuilder(
        int index) {
      return getGamesFieldBuilder().addBuilder(
          index, grpc.GameManagementGetResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc.GameManagementGetResponse games = 1;</code>
     */
    public java.util.List<grpc.GameManagementGetResponse.Builder> 
         getGamesBuilderList() {
      return getGamesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        grpc.GameManagementGetResponse, grpc.GameManagementGetResponse.Builder, grpc.GameManagementGetResponseOrBuilder> 
        getGamesFieldBuilder() {
      if (gamesBuilder_ == null) {
        gamesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            grpc.GameManagementGetResponse, grpc.GameManagementGetResponse.Builder, grpc.GameManagementGetResponseOrBuilder>(
                games_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        games_ = null;
      }
      return gamesBuilder_;
    }

    private boolean finished_ ;
    /**
     * <code>bool finished = 2;</code>
     * @return The finished.
     */
    @java.lang.Override
    public boolean getFinished() {
      return finished_;
    }
    /**
     * <code>bool finished = 2;</code>
     * @param value The finished to set.
     * @return This builder for chaining.
     */
    public Builder setFinished(boolean value) {

      finished_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool finished = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFinished() {
      bitField0_ = (bitField0_ & ~0x00000002);
      finished_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 3;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 3;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      message_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      message_ = getDefaultInstance().getMessage();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string message = 3;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      message_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grpc.GameManagementGetAllResponse)
  }

  // @@protoc_insertion_point(class_scope:grpc.GameManagementGetAllResponse)
  private static final grpc.GameManagementGetAllResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.GameManagementGetAllResponse();
  }

  public static grpc.GameManagementGetAllResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GameManagementGetAllResponse>
      PARSER = new com.google.protobuf.AbstractParser<GameManagementGetAllResponse>() {
    @java.lang.Override
    public GameManagementGetAllResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GameManagementGetAllResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GameManagementGetAllResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.GameManagementGetAllResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

