// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.27.2

package grpc;

public interface GameManagementGetListByEventRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.GameManagementGetListByEventRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string eventId = 1;</code>
   * @return The eventId.
   */
  java.lang.String getEventId();
  /**
   * <code>string eventId = 1;</code>
   * @return The bytes for eventId.
   */
  com.google.protobuf.ByteString
      getEventIdBytes();
}
