// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.27.2

package grpc;

/**
 * Protobuf type {@code grpc.GameManagementUpdateQuizQuestionsRequest}
 */
public final class GameManagementUpdateQuizQuestionsRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:grpc.GameManagementUpdateQuizQuestionsRequest)
    GameManagementUpdateQuizQuestionsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      GameManagementUpdateQuizQuestionsRequest.class.getName());
  }
  // Use GameManagementUpdateQuizQuestionsRequest.newBuilder() to construct.
  private GameManagementUpdateQuizQuestionsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GameManagementUpdateQuizQuestionsRequest() {
    gameId_ = "";
    questionIndex_ = emptyIntList();
    newQuestionInfo_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.Service.internal_static_grpc_GameManagementUpdateQuizQuestionsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.Service.internal_static_grpc_GameManagementUpdateQuizQuestionsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.GameManagementUpdateQuizQuestionsRequest.class, grpc.GameManagementUpdateQuizQuestionsRequest.Builder.class);
  }

  public static final int GAMEID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object gameId_ = "";
  /**
   * <code>string gameId = 1;</code>
   * @return The gameId.
   */
  @java.lang.Override
  public java.lang.String getGameId() {
    java.lang.Object ref = gameId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gameId_ = s;
      return s;
    }
  }
  /**
   * <code>string gameId = 1;</code>
   * @return The bytes for gameId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGameIdBytes() {
    java.lang.Object ref = gameId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gameId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUESTIONINDEX_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList questionIndex_ =
      emptyIntList();
  /**
   * <code>repeated int32 questionIndex = 2;</code>
   * @return A list containing the questionIndex.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getQuestionIndexList() {
    return questionIndex_;
  }
  /**
   * <code>repeated int32 questionIndex = 2;</code>
   * @return The count of questionIndex.
   */
  public int getQuestionIndexCount() {
    return questionIndex_.size();
  }
  /**
   * <code>repeated int32 questionIndex = 2;</code>
   * @param index The index of the element to return.
   * @return The questionIndex at the given index.
   */
  public int getQuestionIndex(int index) {
    return questionIndex_.getInt(index);
  }
  private int questionIndexMemoizedSerializedSize = -1;

  public static final int NEWQUESTIONINFO_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<grpc.GameManagementQuestion> newQuestionInfo_;
  /**
   * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
   */
  @java.lang.Override
  public java.util.List<grpc.GameManagementQuestion> getNewQuestionInfoList() {
    return newQuestionInfo_;
  }
  /**
   * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends grpc.GameManagementQuestionOrBuilder> 
      getNewQuestionInfoOrBuilderList() {
    return newQuestionInfo_;
  }
  /**
   * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
   */
  @java.lang.Override
  public int getNewQuestionInfoCount() {
    return newQuestionInfo_.size();
  }
  /**
   * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
   */
  @java.lang.Override
  public grpc.GameManagementQuestion getNewQuestionInfo(int index) {
    return newQuestionInfo_.get(index);
  }
  /**
   * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
   */
  @java.lang.Override
  public grpc.GameManagementQuestionOrBuilder getNewQuestionInfoOrBuilder(
      int index) {
    return newQuestionInfo_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(gameId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, gameId_);
    }
    if (getQuestionIndexList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(questionIndexMemoizedSerializedSize);
    }
    for (int i = 0; i < questionIndex_.size(); i++) {
      output.writeInt32NoTag(questionIndex_.getInt(i));
    }
    for (int i = 0; i < newQuestionInfo_.size(); i++) {
      output.writeMessage(3, newQuestionInfo_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(gameId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, gameId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < questionIndex_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(questionIndex_.getInt(i));
      }
      size += dataSize;
      if (!getQuestionIndexList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      questionIndexMemoizedSerializedSize = dataSize;
    }
    for (int i = 0; i < newQuestionInfo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, newQuestionInfo_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.GameManagementUpdateQuizQuestionsRequest)) {
      return super.equals(obj);
    }
    grpc.GameManagementUpdateQuizQuestionsRequest other = (grpc.GameManagementUpdateQuizQuestionsRequest) obj;

    if (!getGameId()
        .equals(other.getGameId())) return false;
    if (!getQuestionIndexList()
        .equals(other.getQuestionIndexList())) return false;
    if (!getNewQuestionInfoList()
        .equals(other.getNewQuestionInfoList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + GAMEID_FIELD_NUMBER;
    hash = (53 * hash) + getGameId().hashCode();
    if (getQuestionIndexCount() > 0) {
      hash = (37 * hash) + QUESTIONINDEX_FIELD_NUMBER;
      hash = (53 * hash) + getQuestionIndexList().hashCode();
    }
    if (getNewQuestionInfoCount() > 0) {
      hash = (37 * hash) + NEWQUESTIONINFO_FIELD_NUMBER;
      hash = (53 * hash) + getNewQuestionInfoList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.GameManagementUpdateQuizQuestionsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.GameManagementUpdateQuizQuestionsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.GameManagementUpdateQuizQuestionsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.GameManagementUpdateQuizQuestionsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.GameManagementUpdateQuizQuestionsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.GameManagementUpdateQuizQuestionsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.GameManagementUpdateQuizQuestionsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static grpc.GameManagementUpdateQuizQuestionsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static grpc.GameManagementUpdateQuizQuestionsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static grpc.GameManagementUpdateQuizQuestionsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.GameManagementUpdateQuizQuestionsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static grpc.GameManagementUpdateQuizQuestionsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.GameManagementUpdateQuizQuestionsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.GameManagementUpdateQuizQuestionsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.GameManagementUpdateQuizQuestionsRequest)
      grpc.GameManagementUpdateQuizQuestionsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.Service.internal_static_grpc_GameManagementUpdateQuizQuestionsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.Service.internal_static_grpc_GameManagementUpdateQuizQuestionsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.GameManagementUpdateQuizQuestionsRequest.class, grpc.GameManagementUpdateQuizQuestionsRequest.Builder.class);
    }

    // Construct using grpc.GameManagementUpdateQuizQuestionsRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      gameId_ = "";
      questionIndex_ = emptyIntList();
      if (newQuestionInfoBuilder_ == null) {
        newQuestionInfo_ = java.util.Collections.emptyList();
      } else {
        newQuestionInfo_ = null;
        newQuestionInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.Service.internal_static_grpc_GameManagementUpdateQuizQuestionsRequest_descriptor;
    }

    @java.lang.Override
    public grpc.GameManagementUpdateQuizQuestionsRequest getDefaultInstanceForType() {
      return grpc.GameManagementUpdateQuizQuestionsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.GameManagementUpdateQuizQuestionsRequest build() {
      grpc.GameManagementUpdateQuizQuestionsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.GameManagementUpdateQuizQuestionsRequest buildPartial() {
      grpc.GameManagementUpdateQuizQuestionsRequest result = new grpc.GameManagementUpdateQuizQuestionsRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(grpc.GameManagementUpdateQuizQuestionsRequest result) {
      if (newQuestionInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          newQuestionInfo_ = java.util.Collections.unmodifiableList(newQuestionInfo_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.newQuestionInfo_ = newQuestionInfo_;
      } else {
        result.newQuestionInfo_ = newQuestionInfoBuilder_.build();
      }
    }

    private void buildPartial0(grpc.GameManagementUpdateQuizQuestionsRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.gameId_ = gameId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        questionIndex_.makeImmutable();
        result.questionIndex_ = questionIndex_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.GameManagementUpdateQuizQuestionsRequest) {
        return mergeFrom((grpc.GameManagementUpdateQuizQuestionsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.GameManagementUpdateQuizQuestionsRequest other) {
      if (other == grpc.GameManagementUpdateQuizQuestionsRequest.getDefaultInstance()) return this;
      if (!other.getGameId().isEmpty()) {
        gameId_ = other.gameId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.questionIndex_.isEmpty()) {
        if (questionIndex_.isEmpty()) {
          questionIndex_ = other.questionIndex_;
          questionIndex_.makeImmutable();
          bitField0_ |= 0x00000002;
        } else {
          ensureQuestionIndexIsMutable();
          questionIndex_.addAll(other.questionIndex_);
        }
        onChanged();
      }
      if (newQuestionInfoBuilder_ == null) {
        if (!other.newQuestionInfo_.isEmpty()) {
          if (newQuestionInfo_.isEmpty()) {
            newQuestionInfo_ = other.newQuestionInfo_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureNewQuestionInfoIsMutable();
            newQuestionInfo_.addAll(other.newQuestionInfo_);
          }
          onChanged();
        }
      } else {
        if (!other.newQuestionInfo_.isEmpty()) {
          if (newQuestionInfoBuilder_.isEmpty()) {
            newQuestionInfoBuilder_.dispose();
            newQuestionInfoBuilder_ = null;
            newQuestionInfo_ = other.newQuestionInfo_;
            bitField0_ = (bitField0_ & ~0x00000004);
            newQuestionInfoBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getNewQuestionInfoFieldBuilder() : null;
          } else {
            newQuestionInfoBuilder_.addAllMessages(other.newQuestionInfo_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              gameId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              int v = input.readInt32();
              ensureQuestionIndexIsMutable();
              questionIndex_.addInt(v);
              break;
            } // case 16
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureQuestionIndexIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                questionIndex_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            } // case 18
            case 26: {
              grpc.GameManagementQuestion m =
                  input.readMessage(
                      grpc.GameManagementQuestion.parser(),
                      extensionRegistry);
              if (newQuestionInfoBuilder_ == null) {
                ensureNewQuestionInfoIsMutable();
                newQuestionInfo_.add(m);
              } else {
                newQuestionInfoBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object gameId_ = "";
    /**
     * <code>string gameId = 1;</code>
     * @return The gameId.
     */
    public java.lang.String getGameId() {
      java.lang.Object ref = gameId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gameId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string gameId = 1;</code>
     * @return The bytes for gameId.
     */
    public com.google.protobuf.ByteString
        getGameIdBytes() {
      java.lang.Object ref = gameId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string gameId = 1;</code>
     * @param value The gameId to set.
     * @return This builder for chaining.
     */
    public Builder setGameId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      gameId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string gameId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearGameId() {
      gameId_ = getDefaultInstance().getGameId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string gameId = 1;</code>
     * @param value The bytes for gameId to set.
     * @return This builder for chaining.
     */
    public Builder setGameIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      gameId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList questionIndex_ = emptyIntList();
    private void ensureQuestionIndexIsMutable() {
      if (!questionIndex_.isModifiable()) {
        questionIndex_ = makeMutableCopy(questionIndex_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated int32 questionIndex = 2;</code>
     * @return A list containing the questionIndex.
     */
    public java.util.List<java.lang.Integer>
        getQuestionIndexList() {
      questionIndex_.makeImmutable();
      return questionIndex_;
    }
    /**
     * <code>repeated int32 questionIndex = 2;</code>
     * @return The count of questionIndex.
     */
    public int getQuestionIndexCount() {
      return questionIndex_.size();
    }
    /**
     * <code>repeated int32 questionIndex = 2;</code>
     * @param index The index of the element to return.
     * @return The questionIndex at the given index.
     */
    public int getQuestionIndex(int index) {
      return questionIndex_.getInt(index);
    }
    /**
     * <code>repeated int32 questionIndex = 2;</code>
     * @param index The index to set the value at.
     * @param value The questionIndex to set.
     * @return This builder for chaining.
     */
    public Builder setQuestionIndex(
        int index, int value) {

      ensureQuestionIndexIsMutable();
      questionIndex_.setInt(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 questionIndex = 2;</code>
     * @param value The questionIndex to add.
     * @return This builder for chaining.
     */
    public Builder addQuestionIndex(int value) {

      ensureQuestionIndexIsMutable();
      questionIndex_.addInt(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 questionIndex = 2;</code>
     * @param values The questionIndex to add.
     * @return This builder for chaining.
     */
    public Builder addAllQuestionIndex(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureQuestionIndexIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, questionIndex_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 questionIndex = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuestionIndex() {
      questionIndex_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private java.util.List<grpc.GameManagementQuestion> newQuestionInfo_ =
      java.util.Collections.emptyList();
    private void ensureNewQuestionInfoIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        newQuestionInfo_ = new java.util.ArrayList<grpc.GameManagementQuestion>(newQuestionInfo_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        grpc.GameManagementQuestion, grpc.GameManagementQuestion.Builder, grpc.GameManagementQuestionOrBuilder> newQuestionInfoBuilder_;

    /**
     * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
     */
    public java.util.List<grpc.GameManagementQuestion> getNewQuestionInfoList() {
      if (newQuestionInfoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(newQuestionInfo_);
      } else {
        return newQuestionInfoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
     */
    public int getNewQuestionInfoCount() {
      if (newQuestionInfoBuilder_ == null) {
        return newQuestionInfo_.size();
      } else {
        return newQuestionInfoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
     */
    public grpc.GameManagementQuestion getNewQuestionInfo(int index) {
      if (newQuestionInfoBuilder_ == null) {
        return newQuestionInfo_.get(index);
      } else {
        return newQuestionInfoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
     */
    public Builder setNewQuestionInfo(
        int index, grpc.GameManagementQuestion value) {
      if (newQuestionInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewQuestionInfoIsMutable();
        newQuestionInfo_.set(index, value);
        onChanged();
      } else {
        newQuestionInfoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
     */
    public Builder setNewQuestionInfo(
        int index, grpc.GameManagementQuestion.Builder builderForValue) {
      if (newQuestionInfoBuilder_ == null) {
        ensureNewQuestionInfoIsMutable();
        newQuestionInfo_.set(index, builderForValue.build());
        onChanged();
      } else {
        newQuestionInfoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
     */
    public Builder addNewQuestionInfo(grpc.GameManagementQuestion value) {
      if (newQuestionInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewQuestionInfoIsMutable();
        newQuestionInfo_.add(value);
        onChanged();
      } else {
        newQuestionInfoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
     */
    public Builder addNewQuestionInfo(
        int index, grpc.GameManagementQuestion value) {
      if (newQuestionInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewQuestionInfoIsMutable();
        newQuestionInfo_.add(index, value);
        onChanged();
      } else {
        newQuestionInfoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
     */
    public Builder addNewQuestionInfo(
        grpc.GameManagementQuestion.Builder builderForValue) {
      if (newQuestionInfoBuilder_ == null) {
        ensureNewQuestionInfoIsMutable();
        newQuestionInfo_.add(builderForValue.build());
        onChanged();
      } else {
        newQuestionInfoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
     */
    public Builder addNewQuestionInfo(
        int index, grpc.GameManagementQuestion.Builder builderForValue) {
      if (newQuestionInfoBuilder_ == null) {
        ensureNewQuestionInfoIsMutable();
        newQuestionInfo_.add(index, builderForValue.build());
        onChanged();
      } else {
        newQuestionInfoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
     */
    public Builder addAllNewQuestionInfo(
        java.lang.Iterable<? extends grpc.GameManagementQuestion> values) {
      if (newQuestionInfoBuilder_ == null) {
        ensureNewQuestionInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, newQuestionInfo_);
        onChanged();
      } else {
        newQuestionInfoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
     */
    public Builder clearNewQuestionInfo() {
      if (newQuestionInfoBuilder_ == null) {
        newQuestionInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        newQuestionInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
     */
    public Builder removeNewQuestionInfo(int index) {
      if (newQuestionInfoBuilder_ == null) {
        ensureNewQuestionInfoIsMutable();
        newQuestionInfo_.remove(index);
        onChanged();
      } else {
        newQuestionInfoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
     */
    public grpc.GameManagementQuestion.Builder getNewQuestionInfoBuilder(
        int index) {
      return getNewQuestionInfoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
     */
    public grpc.GameManagementQuestionOrBuilder getNewQuestionInfoOrBuilder(
        int index) {
      if (newQuestionInfoBuilder_ == null) {
        return newQuestionInfo_.get(index);  } else {
        return newQuestionInfoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
     */
    public java.util.List<? extends grpc.GameManagementQuestionOrBuilder> 
         getNewQuestionInfoOrBuilderList() {
      if (newQuestionInfoBuilder_ != null) {
        return newQuestionInfoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(newQuestionInfo_);
      }
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
     */
    public grpc.GameManagementQuestion.Builder addNewQuestionInfoBuilder() {
      return getNewQuestionInfoFieldBuilder().addBuilder(
          grpc.GameManagementQuestion.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
     */
    public grpc.GameManagementQuestion.Builder addNewQuestionInfoBuilder(
        int index) {
      return getNewQuestionInfoFieldBuilder().addBuilder(
          index, grpc.GameManagementQuestion.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
     */
    public java.util.List<grpc.GameManagementQuestion.Builder> 
         getNewQuestionInfoBuilderList() {
      return getNewQuestionInfoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        grpc.GameManagementQuestion, grpc.GameManagementQuestion.Builder, grpc.GameManagementQuestionOrBuilder> 
        getNewQuestionInfoFieldBuilder() {
      if (newQuestionInfoBuilder_ == null) {
        newQuestionInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            grpc.GameManagementQuestion, grpc.GameManagementQuestion.Builder, grpc.GameManagementQuestionOrBuilder>(
                newQuestionInfo_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        newQuestionInfo_ = null;
      }
      return newQuestionInfoBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:grpc.GameManagementUpdateQuizQuestionsRequest)
  }

  // @@protoc_insertion_point(class_scope:grpc.GameManagementUpdateQuizQuestionsRequest)
  private static final grpc.GameManagementUpdateQuizQuestionsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.GameManagementUpdateQuizQuestionsRequest();
  }

  public static grpc.GameManagementUpdateQuizQuestionsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GameManagementUpdateQuizQuestionsRequest>
      PARSER = new com.google.protobuf.AbstractParser<GameManagementUpdateQuizQuestionsRequest>() {
    @java.lang.Override
    public GameManagementUpdateQuizQuestionsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GameManagementUpdateQuizQuestionsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GameManagementUpdateQuizQuestionsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.GameManagementUpdateQuizQuestionsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

