// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.27.2

package grpc;

public interface GameManagementQuizAnswerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.GameManagementQuizAnswerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string gameId = 1;</code>
   * @return The gameId.
   */
  java.lang.String getGameId();
  /**
   * <code>string gameId = 1;</code>
   * @return The bytes for gameId.
   */
  com.google.protobuf.ByteString
      getGameIdBytes();

  /**
   * <code>string userId = 2;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 2;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>repeated int32 answers = 3;</code>
   * @return A list containing the answers.
   */
  java.util.List<java.lang.Integer> getAnswersList();
  /**
   * <code>repeated int32 answers = 3;</code>
   * @return The count of answers.
   */
  int getAnswersCount();
  /**
   * <code>repeated int32 answers = 3;</code>
   * @param index The index of the element to return.
   * @return The answers at the given index.
   */
  int getAnswers(int index);

  /**
   * <code>int32 score = 4;</code>
   * @return The score.
   */
  int getScore();
}
