// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.27.2

package grpc;

public interface GameManagementShakeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.GameManagementShakeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool finished = 1;</code>
   * @return The finished.
   */
  boolean getFinished();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int64 shakeResult = 3;</code>
   * @return The shakeResult.
   */
  long getShakeResult();
}
