// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.27.2

package grpc;

public interface GameManagementAddQuizQuestionsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.GameManagementAddQuizQuestionsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string gameId = 1;</code>
   * @return The gameId.
   */
  java.lang.String getGameId();
  /**
   * <code>string gameId = 1;</code>
   * @return The bytes for gameId.
   */
  com.google.protobuf.ByteString
      getGameIdBytes();

  /**
   * <code>repeated .grpc.GameManagementQuestion questions = 2;</code>
   */
  java.util.List<grpc.GameManagementQuestion> 
      getQuestionsList();
  /**
   * <code>repeated .grpc.GameManagementQuestion questions = 2;</code>
   */
  grpc.GameManagementQuestion getQuestions(int index);
  /**
   * <code>repeated .grpc.GameManagementQuestion questions = 2;</code>
   */
  int getQuestionsCount();
  /**
   * <code>repeated .grpc.GameManagementQuestion questions = 2;</code>
   */
  java.util.List<? extends grpc.GameManagementQuestionOrBuilder> 
      getQuestionsOrBuilderList();
  /**
   * <code>repeated .grpc.GameManagementQuestion questions = 2;</code>
   */
  grpc.GameManagementQuestionOrBuilder getQuestionsOrBuilder(
      int index);
}
