// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.27.2

package grpc;

public interface GameManagementGetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.GameManagementGetRequest)
    com.google.protobuf.MessageOrBuilder {
}
