// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.27.2

package grpc;

public interface GameManagementQuizQuestionsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.GameManagementQuizQuestionsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool finished = 1;</code>
   * @return The finished.
   */
  boolean getFinished();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .grpc.GameManagementQuestion questions = 3;</code>
   */
  java.util.List<grpc.GameManagementQuestion> 
      getQuestionsList();
  /**
   * <code>repeated .grpc.GameManagementQuestion questions = 3;</code>
   */
  grpc.GameManagementQuestion getQuestions(int index);
  /**
   * <code>repeated .grpc.GameManagementQuestion questions = 3;</code>
   */
  int getQuestionsCount();
  /**
   * <code>repeated .grpc.GameManagementQuestion questions = 3;</code>
   */
  java.util.List<? extends grpc.GameManagementQuestionOrBuilder> 
      getQuestionsOrBuilderList();
  /**
   * <code>repeated .grpc.GameManagementQuestion questions = 3;</code>
   */
  grpc.GameManagementQuestionOrBuilder getQuestionsOrBuilder(
      int index);
}
