// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.27.2

package grpc;

public interface GameManagementUpdateQuizQuestionsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.GameManagementUpdateQuizQuestionsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string gameId = 1;</code>
   * @return The gameId.
   */
  java.lang.String getGameId();
  /**
   * <code>string gameId = 1;</code>
   * @return The bytes for gameId.
   */
  com.google.protobuf.ByteString
      getGameIdBytes();

  /**
   * <code>repeated int32 questionIndex = 2;</code>
   * @return A list containing the questionIndex.
   */
  java.util.List<java.lang.Integer> getQuestionIndexList();
  /**
   * <code>repeated int32 questionIndex = 2;</code>
   * @return The count of questionIndex.
   */
  int getQuestionIndexCount();
  /**
   * <code>repeated int32 questionIndex = 2;</code>
   * @param index The index of the element to return.
   * @return The questionIndex at the given index.
   */
  int getQuestionIndex(int index);

  /**
   * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
   */
  java.util.List<grpc.GameManagementQuestion> 
      getNewQuestionInfoList();
  /**
   * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
   */
  grpc.GameManagementQuestion getNewQuestionInfo(int index);
  /**
   * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
   */
  int getNewQuestionInfoCount();
  /**
   * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
   */
  java.util.List<? extends grpc.GameManagementQuestionOrBuilder> 
      getNewQuestionInfoOrBuilderList();
  /**
   * <code>repeated .grpc.GameManagementQuestion newQuestionInfo = 3;</code>
   */
  grpc.GameManagementQuestionOrBuilder getNewQuestionInfoOrBuilder(
      int index);
}
