// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.27.2

package grpc;

/**
 * Protobuf type {@code grpc.GameManagementQuestion}
 */
public final class GameManagementQuestion extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:grpc.GameManagementQuestion)
    GameManagementQuestionOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      GameManagementQuestion.class.getName());
  }
  // Use GameManagementQuestion.newBuilder() to construct.
  private GameManagementQuestion(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GameManagementQuestion() {
    text_ = "";
    options_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.Service.internal_static_grpc_GameManagementQuestion_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.Service.internal_static_grpc_GameManagementQuestion_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.GameManagementQuestion.class, grpc.GameManagementQuestion.Builder.class);
  }

  public static final int TEXT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object text_ = "";
  /**
   * <code>string text = 1;</code>
   * @return The text.
   */
  @java.lang.Override
  public java.lang.String getText() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      text_ = s;
      return s;
    }
  }
  /**
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextBytes() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      text_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPTIONS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList options_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string options = 2;</code>
   * @return A list containing the options.
   */
  public com.google.protobuf.ProtocolStringList
      getOptionsList() {
    return options_;
  }
  /**
   * <code>repeated string options = 2;</code>
   * @return The count of options.
   */
  public int getOptionsCount() {
    return options_.size();
  }
  /**
   * <code>repeated string options = 2;</code>
   * @param index The index of the element to return.
   * @return The options at the given index.
   */
  public java.lang.String getOptions(int index) {
    return options_.get(index);
  }
  /**
   * <code>repeated string options = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the options at the given index.
   */
  public com.google.protobuf.ByteString
      getOptionsBytes(int index) {
    return options_.getByteString(index);
  }

  public static final int CORRECTANSWER_FIELD_NUMBER = 3;
  private int correctAnswer_ = 0;
  /**
   * <code>int32 correctAnswer = 3;</code>
   * @return The correctAnswer.
   */
  @java.lang.Override
  public int getCorrectAnswer() {
    return correctAnswer_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, text_);
    }
    for (int i = 0; i < options_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, options_.getRaw(i));
    }
    if (correctAnswer_ != 0) {
      output.writeInt32(3, correctAnswer_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, text_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < options_.size(); i++) {
        dataSize += computeStringSizeNoTag(options_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getOptionsList().size();
    }
    if (correctAnswer_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, correctAnswer_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.GameManagementQuestion)) {
      return super.equals(obj);
    }
    grpc.GameManagementQuestion other = (grpc.GameManagementQuestion) obj;

    if (!getText()
        .equals(other.getText())) return false;
    if (!getOptionsList()
        .equals(other.getOptionsList())) return false;
    if (getCorrectAnswer()
        != other.getCorrectAnswer()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getText().hashCode();
    if (getOptionsCount() > 0) {
      hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOptionsList().hashCode();
    }
    hash = (37 * hash) + CORRECTANSWER_FIELD_NUMBER;
    hash = (53 * hash) + getCorrectAnswer();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.GameManagementQuestion parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.GameManagementQuestion parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.GameManagementQuestion parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.GameManagementQuestion parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.GameManagementQuestion parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.GameManagementQuestion parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.GameManagementQuestion parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static grpc.GameManagementQuestion parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static grpc.GameManagementQuestion parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static grpc.GameManagementQuestion parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.GameManagementQuestion parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static grpc.GameManagementQuestion parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.GameManagementQuestion prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.GameManagementQuestion}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.GameManagementQuestion)
      grpc.GameManagementQuestionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.Service.internal_static_grpc_GameManagementQuestion_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.Service.internal_static_grpc_GameManagementQuestion_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.GameManagementQuestion.class, grpc.GameManagementQuestion.Builder.class);
    }

    // Construct using grpc.GameManagementQuestion.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      text_ = "";
      options_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      correctAnswer_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.Service.internal_static_grpc_GameManagementQuestion_descriptor;
    }

    @java.lang.Override
    public grpc.GameManagementQuestion getDefaultInstanceForType() {
      return grpc.GameManagementQuestion.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.GameManagementQuestion build() {
      grpc.GameManagementQuestion result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.GameManagementQuestion buildPartial() {
      grpc.GameManagementQuestion result = new grpc.GameManagementQuestion(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(grpc.GameManagementQuestion result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.text_ = text_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        options_.makeImmutable();
        result.options_ = options_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.correctAnswer_ = correctAnswer_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.GameManagementQuestion) {
        return mergeFrom((grpc.GameManagementQuestion)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.GameManagementQuestion other) {
      if (other == grpc.GameManagementQuestion.getDefaultInstance()) return this;
      if (!other.getText().isEmpty()) {
        text_ = other.text_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.options_.isEmpty()) {
        if (options_.isEmpty()) {
          options_ = other.options_;
          bitField0_ |= 0x00000002;
        } else {
          ensureOptionsIsMutable();
          options_.addAll(other.options_);
        }
        onChanged();
      }
      if (other.getCorrectAnswer() != 0) {
        setCorrectAnswer(other.getCorrectAnswer());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              text_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureOptionsIsMutable();
              options_.add(s);
              break;
            } // case 18
            case 24: {
              correctAnswer_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object text_ = "";
    /**
     * <code>string text = 1;</code>
     * @return The text.
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string text = 1;</code>
     * @return The bytes for text.
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string text = 1;</code>
     * @param value The text to set.
     * @return This builder for chaining.
     */
    public Builder setText(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      text_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string text = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearText() {
      text_ = getDefaultInstance().getText();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string text = 1;</code>
     * @param value The bytes for text to set.
     * @return This builder for chaining.
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      text_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList options_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureOptionsIsMutable() {
      if (!options_.isModifiable()) {
        options_ = new com.google.protobuf.LazyStringArrayList(options_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated string options = 2;</code>
     * @return A list containing the options.
     */
    public com.google.protobuf.ProtocolStringList
        getOptionsList() {
      options_.makeImmutable();
      return options_;
    }
    /**
     * <code>repeated string options = 2;</code>
     * @return The count of options.
     */
    public int getOptionsCount() {
      return options_.size();
    }
    /**
     * <code>repeated string options = 2;</code>
     * @param index The index of the element to return.
     * @return The options at the given index.
     */
    public java.lang.String getOptions(int index) {
      return options_.get(index);
    }
    /**
     * <code>repeated string options = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the options at the given index.
     */
    public com.google.protobuf.ByteString
        getOptionsBytes(int index) {
      return options_.getByteString(index);
    }
    /**
     * <code>repeated string options = 2;</code>
     * @param index The index to set the value at.
     * @param value The options to set.
     * @return This builder for chaining.
     */
    public Builder setOptions(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureOptionsIsMutable();
      options_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string options = 2;</code>
     * @param value The options to add.
     * @return This builder for chaining.
     */
    public Builder addOptions(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureOptionsIsMutable();
      options_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string options = 2;</code>
     * @param values The options to add.
     * @return This builder for chaining.
     */
    public Builder addAllOptions(
        java.lang.Iterable<java.lang.String> values) {
      ensureOptionsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, options_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string options = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOptions() {
      options_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string options = 2;</code>
     * @param value The bytes of the options to add.
     * @return This builder for chaining.
     */
    public Builder addOptionsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureOptionsIsMutable();
      options_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int correctAnswer_ ;
    /**
     * <code>int32 correctAnswer = 3;</code>
     * @return The correctAnswer.
     */
    @java.lang.Override
    public int getCorrectAnswer() {
      return correctAnswer_;
    }
    /**
     * <code>int32 correctAnswer = 3;</code>
     * @param value The correctAnswer to set.
     * @return This builder for chaining.
     */
    public Builder setCorrectAnswer(int value) {

      correctAnswer_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 correctAnswer = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCorrectAnswer() {
      bitField0_ = (bitField0_ & ~0x00000004);
      correctAnswer_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grpc.GameManagementQuestion)
  }

  // @@protoc_insertion_point(class_scope:grpc.GameManagementQuestion)
  private static final grpc.GameManagementQuestion DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.GameManagementQuestion();
  }

  public static grpc.GameManagementQuestion getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GameManagementQuestion>
      PARSER = new com.google.protobuf.AbstractParser<GameManagementQuestion>() {
    @java.lang.Override
    public GameManagementQuestion parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GameManagementQuestion> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GameManagementQuestion> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.GameManagementQuestion getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

