// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.27.2

package grpc;

/**
 * Protobuf type {@code grpc.GameManagementGetResponse}
 */
public final class GameManagementGetResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:grpc.GameManagementGetResponse)
    GameManagementGetResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      GameManagementGetResponse.class.getName());
  }
  // Use GameManagementGetResponse.newBuilder() to construct.
  private GameManagementGetResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GameManagementGetResponse() {
    id_ = "";
    name_ = "";
    image_ = "";
    type_ = "";
    tutorial_ = "";
    status_ = "";
    questions_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.Service.internal_static_grpc_GameManagementGetResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.Service.internal_static_grpc_GameManagementGetResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.GameManagementGetResponse.class, grpc.GameManagementGetResponse.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object image_ = "";
  /**
   * <code>string image = 3;</code>
   * @return The image.
   */
  @java.lang.Override
  public java.lang.String getImage() {
    java.lang.Object ref = image_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      image_ = s;
      return s;
    }
  }
  /**
   * <code>string image = 3;</code>
   * @return The bytes for image.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getImageBytes() {
    java.lang.Object ref = image_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      image_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object type_ = "";
  /**
   * <code>string type = 4;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 4;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALLOWEDITEMTRADE_FIELD_NUMBER = 5;
  private boolean allowedItemTrade_ = false;
  /**
   * <code>bool allowedItemTrade = 5;</code>
   * @return The allowedItemTrade.
   */
  @java.lang.Override
  public boolean getAllowedItemTrade() {
    return allowedItemTrade_;
  }

  public static final int TUTORIAL_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tutorial_ = "";
  /**
   * <code>string tutorial = 6;</code>
   * @return The tutorial.
   */
  @java.lang.Override
  public java.lang.String getTutorial() {
    java.lang.Object ref = tutorial_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tutorial_ = s;
      return s;
    }
  }
  /**
   * <code>string tutorial = 6;</code>
   * @return The bytes for tutorial.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTutorialBytes() {
    java.lang.Object ref = tutorial_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tutorial_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <code>string status = 7;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 7;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STARTTIME_FIELD_NUMBER = 8;
  private long startTime_ = 0L;
  /**
   * <code>int64 startTime = 8;</code>
   * @return The startTime.
   */
  @java.lang.Override
  public long getStartTime() {
    return startTime_;
  }

  public static final int ENDTIME_FIELD_NUMBER = 9;
  private long endTime_ = 0L;
  /**
   * <code>int64 endTime = 9;</code>
   * @return The endTime.
   */
  @java.lang.Override
  public long getEndTime() {
    return endTime_;
  }

  public static final int MAXPLAYERS_FIELD_NUMBER = 10;
  private int maxPlayers_ = 0;
  /**
   * <code>int32 maxPlayers = 10;</code>
   * @return The maxPlayers.
   */
  @java.lang.Override
  public int getMaxPlayers() {
    return maxPlayers_;
  }

  public static final int DURATION_FIELD_NUMBER = 11;
  private int duration_ = 0;
  /**
   * <code>int32 duration = 11;</code>
   * @return The duration.
   */
  @java.lang.Override
  public int getDuration() {
    return duration_;
  }

  public static final int QUESTIONS_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private java.util.List<grpc.GameManagementQuestion> questions_;
  /**
   * <code>repeated .grpc.GameManagementQuestion questions = 12;</code>
   */
  @java.lang.Override
  public java.util.List<grpc.GameManagementQuestion> getQuestionsList() {
    return questions_;
  }
  /**
   * <code>repeated .grpc.GameManagementQuestion questions = 12;</code>
   */
  @java.lang.Override
  public java.util.List<? extends grpc.GameManagementQuestionOrBuilder> 
      getQuestionsOrBuilderList() {
    return questions_;
  }
  /**
   * <code>repeated .grpc.GameManagementQuestion questions = 12;</code>
   */
  @java.lang.Override
  public int getQuestionsCount() {
    return questions_.size();
  }
  /**
   * <code>repeated .grpc.GameManagementQuestion questions = 12;</code>
   */
  @java.lang.Override
  public grpc.GameManagementQuestion getQuestions(int index) {
    return questions_.get(index);
  }
  /**
   * <code>repeated .grpc.GameManagementQuestion questions = 12;</code>
   */
  @java.lang.Override
  public grpc.GameManagementQuestionOrBuilder getQuestionsOrBuilder(
      int index) {
    return questions_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(image_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, image_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, type_);
    }
    if (allowedItemTrade_ != false) {
      output.writeBool(5, allowedItemTrade_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tutorial_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, tutorial_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, status_);
    }
    if (startTime_ != 0L) {
      output.writeInt64(8, startTime_);
    }
    if (endTime_ != 0L) {
      output.writeInt64(9, endTime_);
    }
    if (maxPlayers_ != 0) {
      output.writeInt32(10, maxPlayers_);
    }
    if (duration_ != 0) {
      output.writeInt32(11, duration_);
    }
    for (int i = 0; i < questions_.size(); i++) {
      output.writeMessage(12, questions_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(image_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, image_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, type_);
    }
    if (allowedItemTrade_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, allowedItemTrade_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tutorial_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, tutorial_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, status_);
    }
    if (startTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, startTime_);
    }
    if (endTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, endTime_);
    }
    if (maxPlayers_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, maxPlayers_);
    }
    if (duration_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, duration_);
    }
    for (int i = 0; i < questions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, questions_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.GameManagementGetResponse)) {
      return super.equals(obj);
    }
    grpc.GameManagementGetResponse other = (grpc.GameManagementGetResponse) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getImage()
        .equals(other.getImage())) return false;
    if (!getType()
        .equals(other.getType())) return false;
    if (getAllowedItemTrade()
        != other.getAllowedItemTrade()) return false;
    if (!getTutorial()
        .equals(other.getTutorial())) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (getStartTime()
        != other.getStartTime()) return false;
    if (getEndTime()
        != other.getEndTime()) return false;
    if (getMaxPlayers()
        != other.getMaxPlayers()) return false;
    if (getDuration()
        != other.getDuration()) return false;
    if (!getQuestionsList()
        .equals(other.getQuestionsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + IMAGE_FIELD_NUMBER;
    hash = (53 * hash) + getImage().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + ALLOWEDITEMTRADE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAllowedItemTrade());
    hash = (37 * hash) + TUTORIAL_FIELD_NUMBER;
    hash = (53 * hash) + getTutorial().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartTime());
    hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndTime());
    hash = (37 * hash) + MAXPLAYERS_FIELD_NUMBER;
    hash = (53 * hash) + getMaxPlayers();
    hash = (37 * hash) + DURATION_FIELD_NUMBER;
    hash = (53 * hash) + getDuration();
    if (getQuestionsCount() > 0) {
      hash = (37 * hash) + QUESTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getQuestionsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.GameManagementGetResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.GameManagementGetResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.GameManagementGetResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.GameManagementGetResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.GameManagementGetResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.GameManagementGetResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.GameManagementGetResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static grpc.GameManagementGetResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static grpc.GameManagementGetResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static grpc.GameManagementGetResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.GameManagementGetResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static grpc.GameManagementGetResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.GameManagementGetResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.GameManagementGetResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.GameManagementGetResponse)
      grpc.GameManagementGetResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.Service.internal_static_grpc_GameManagementGetResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.Service.internal_static_grpc_GameManagementGetResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.GameManagementGetResponse.class, grpc.GameManagementGetResponse.Builder.class);
    }

    // Construct using grpc.GameManagementGetResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      name_ = "";
      image_ = "";
      type_ = "";
      allowedItemTrade_ = false;
      tutorial_ = "";
      status_ = "";
      startTime_ = 0L;
      endTime_ = 0L;
      maxPlayers_ = 0;
      duration_ = 0;
      if (questionsBuilder_ == null) {
        questions_ = java.util.Collections.emptyList();
      } else {
        questions_ = null;
        questionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000800);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.Service.internal_static_grpc_GameManagementGetResponse_descriptor;
    }

    @java.lang.Override
    public grpc.GameManagementGetResponse getDefaultInstanceForType() {
      return grpc.GameManagementGetResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.GameManagementGetResponse build() {
      grpc.GameManagementGetResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.GameManagementGetResponse buildPartial() {
      grpc.GameManagementGetResponse result = new grpc.GameManagementGetResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(grpc.GameManagementGetResponse result) {
      if (questionsBuilder_ == null) {
        if (((bitField0_ & 0x00000800) != 0)) {
          questions_ = java.util.Collections.unmodifiableList(questions_);
          bitField0_ = (bitField0_ & ~0x00000800);
        }
        result.questions_ = questions_;
      } else {
        result.questions_ = questionsBuilder_.build();
      }
    }

    private void buildPartial0(grpc.GameManagementGetResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.image_ = image_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.allowedItemTrade_ = allowedItemTrade_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.tutorial_ = tutorial_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.startTime_ = startTime_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.endTime_ = endTime_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.maxPlayers_ = maxPlayers_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.duration_ = duration_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.GameManagementGetResponse) {
        return mergeFrom((grpc.GameManagementGetResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.GameManagementGetResponse other) {
      if (other == grpc.GameManagementGetResponse.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getImage().isEmpty()) {
        image_ = other.image_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getAllowedItemTrade() != false) {
        setAllowedItemTrade(other.getAllowedItemTrade());
      }
      if (!other.getTutorial().isEmpty()) {
        tutorial_ = other.tutorial_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.getStartTime() != 0L) {
        setStartTime(other.getStartTime());
      }
      if (other.getEndTime() != 0L) {
        setEndTime(other.getEndTime());
      }
      if (other.getMaxPlayers() != 0) {
        setMaxPlayers(other.getMaxPlayers());
      }
      if (other.getDuration() != 0) {
        setDuration(other.getDuration());
      }
      if (questionsBuilder_ == null) {
        if (!other.questions_.isEmpty()) {
          if (questions_.isEmpty()) {
            questions_ = other.questions_;
            bitField0_ = (bitField0_ & ~0x00000800);
          } else {
            ensureQuestionsIsMutable();
            questions_.addAll(other.questions_);
          }
          onChanged();
        }
      } else {
        if (!other.questions_.isEmpty()) {
          if (questionsBuilder_.isEmpty()) {
            questionsBuilder_.dispose();
            questionsBuilder_ = null;
            questions_ = other.questions_;
            bitField0_ = (bitField0_ & ~0x00000800);
            questionsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getQuestionsFieldBuilder() : null;
          } else {
            questionsBuilder_.addAllMessages(other.questions_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              image_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              type_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              allowedItemTrade_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              tutorial_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 64: {
              startTime_ = input.readInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              endTime_ = input.readInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              maxPlayers_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 88: {
              duration_ = input.readInt32();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            case 98: {
              grpc.GameManagementQuestion m =
                  input.readMessage(
                      grpc.GameManagementQuestion.parser(),
                      extensionRegistry);
              if (questionsBuilder_ == null) {
                ensureQuestionsIsMutable();
                questions_.add(m);
              } else {
                questionsBuilder_.addMessage(m);
              }
              break;
            } // case 98
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object image_ = "";
    /**
     * <code>string image = 3;</code>
     * @return The image.
     */
    public java.lang.String getImage() {
      java.lang.Object ref = image_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        image_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string image = 3;</code>
     * @return The bytes for image.
     */
    public com.google.protobuf.ByteString
        getImageBytes() {
      java.lang.Object ref = image_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        image_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string image = 3;</code>
     * @param value The image to set.
     * @return This builder for chaining.
     */
    public Builder setImage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      image_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string image = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearImage() {
      image_ = getDefaultInstance().getImage();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string image = 3;</code>
     * @param value The bytes for image to set.
     * @return This builder for chaining.
     */
    public Builder setImageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      image_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 4;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 4;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 4;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      type_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      type_ = getDefaultInstance().getType();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string type = 4;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      type_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private boolean allowedItemTrade_ ;
    /**
     * <code>bool allowedItemTrade = 5;</code>
     * @return The allowedItemTrade.
     */
    @java.lang.Override
    public boolean getAllowedItemTrade() {
      return allowedItemTrade_;
    }
    /**
     * <code>bool allowedItemTrade = 5;</code>
     * @param value The allowedItemTrade to set.
     * @return This builder for chaining.
     */
    public Builder setAllowedItemTrade(boolean value) {

      allowedItemTrade_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bool allowedItemTrade = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAllowedItemTrade() {
      bitField0_ = (bitField0_ & ~0x00000010);
      allowedItemTrade_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object tutorial_ = "";
    /**
     * <code>string tutorial = 6;</code>
     * @return The tutorial.
     */
    public java.lang.String getTutorial() {
      java.lang.Object ref = tutorial_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tutorial_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tutorial = 6;</code>
     * @return The bytes for tutorial.
     */
    public com.google.protobuf.ByteString
        getTutorialBytes() {
      java.lang.Object ref = tutorial_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tutorial_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tutorial = 6;</code>
     * @param value The tutorial to set.
     * @return This builder for chaining.
     */
    public Builder setTutorial(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tutorial_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string tutorial = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTutorial() {
      tutorial_ = getDefaultInstance().getTutorial();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string tutorial = 6;</code>
     * @param value The bytes for tutorial to set.
     * @return This builder for chaining.
     */
    public Builder setTutorialBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tutorial_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 7;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 7;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 7;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string status = 7;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private long startTime_ ;
    /**
     * <code>int64 startTime = 8;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public long getStartTime() {
      return startTime_;
    }
    /**
     * <code>int64 startTime = 8;</code>
     * @param value The startTime to set.
     * @return This builder for chaining.
     */
    public Builder setStartTime(long value) {

      startTime_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int64 startTime = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartTime() {
      bitField0_ = (bitField0_ & ~0x00000080);
      startTime_ = 0L;
      onChanged();
      return this;
    }

    private long endTime_ ;
    /**
     * <code>int64 endTime = 9;</code>
     * @return The endTime.
     */
    @java.lang.Override
    public long getEndTime() {
      return endTime_;
    }
    /**
     * <code>int64 endTime = 9;</code>
     * @param value The endTime to set.
     * @return This builder for chaining.
     */
    public Builder setEndTime(long value) {

      endTime_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int64 endTime = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndTime() {
      bitField0_ = (bitField0_ & ~0x00000100);
      endTime_ = 0L;
      onChanged();
      return this;
    }

    private int maxPlayers_ ;
    /**
     * <code>int32 maxPlayers = 10;</code>
     * @return The maxPlayers.
     */
    @java.lang.Override
    public int getMaxPlayers() {
      return maxPlayers_;
    }
    /**
     * <code>int32 maxPlayers = 10;</code>
     * @param value The maxPlayers to set.
     * @return This builder for chaining.
     */
    public Builder setMaxPlayers(int value) {

      maxPlayers_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>int32 maxPlayers = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxPlayers() {
      bitField0_ = (bitField0_ & ~0x00000200);
      maxPlayers_ = 0;
      onChanged();
      return this;
    }

    private int duration_ ;
    /**
     * <code>int32 duration = 11;</code>
     * @return The duration.
     */
    @java.lang.Override
    public int getDuration() {
      return duration_;
    }
    /**
     * <code>int32 duration = 11;</code>
     * @param value The duration to set.
     * @return This builder for chaining.
     */
    public Builder setDuration(int value) {

      duration_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>int32 duration = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearDuration() {
      bitField0_ = (bitField0_ & ~0x00000400);
      duration_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<grpc.GameManagementQuestion> questions_ =
      java.util.Collections.emptyList();
    private void ensureQuestionsIsMutable() {
      if (!((bitField0_ & 0x00000800) != 0)) {
        questions_ = new java.util.ArrayList<grpc.GameManagementQuestion>(questions_);
        bitField0_ |= 0x00000800;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        grpc.GameManagementQuestion, grpc.GameManagementQuestion.Builder, grpc.GameManagementQuestionOrBuilder> questionsBuilder_;

    /**
     * <code>repeated .grpc.GameManagementQuestion questions = 12;</code>
     */
    public java.util.List<grpc.GameManagementQuestion> getQuestionsList() {
      if (questionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(questions_);
      } else {
        return questionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion questions = 12;</code>
     */
    public int getQuestionsCount() {
      if (questionsBuilder_ == null) {
        return questions_.size();
      } else {
        return questionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion questions = 12;</code>
     */
    public grpc.GameManagementQuestion getQuestions(int index) {
      if (questionsBuilder_ == null) {
        return questions_.get(index);
      } else {
        return questionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion questions = 12;</code>
     */
    public Builder setQuestions(
        int index, grpc.GameManagementQuestion value) {
      if (questionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQuestionsIsMutable();
        questions_.set(index, value);
        onChanged();
      } else {
        questionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion questions = 12;</code>
     */
    public Builder setQuestions(
        int index, grpc.GameManagementQuestion.Builder builderForValue) {
      if (questionsBuilder_ == null) {
        ensureQuestionsIsMutable();
        questions_.set(index, builderForValue.build());
        onChanged();
      } else {
        questionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion questions = 12;</code>
     */
    public Builder addQuestions(grpc.GameManagementQuestion value) {
      if (questionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQuestionsIsMutable();
        questions_.add(value);
        onChanged();
      } else {
        questionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion questions = 12;</code>
     */
    public Builder addQuestions(
        int index, grpc.GameManagementQuestion value) {
      if (questionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQuestionsIsMutable();
        questions_.add(index, value);
        onChanged();
      } else {
        questionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion questions = 12;</code>
     */
    public Builder addQuestions(
        grpc.GameManagementQuestion.Builder builderForValue) {
      if (questionsBuilder_ == null) {
        ensureQuestionsIsMutable();
        questions_.add(builderForValue.build());
        onChanged();
      } else {
        questionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion questions = 12;</code>
     */
    public Builder addQuestions(
        int index, grpc.GameManagementQuestion.Builder builderForValue) {
      if (questionsBuilder_ == null) {
        ensureQuestionsIsMutable();
        questions_.add(index, builderForValue.build());
        onChanged();
      } else {
        questionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion questions = 12;</code>
     */
    public Builder addAllQuestions(
        java.lang.Iterable<? extends grpc.GameManagementQuestion> values) {
      if (questionsBuilder_ == null) {
        ensureQuestionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, questions_);
        onChanged();
      } else {
        questionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion questions = 12;</code>
     */
    public Builder clearQuestions() {
      if (questionsBuilder_ == null) {
        questions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000800);
        onChanged();
      } else {
        questionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion questions = 12;</code>
     */
    public Builder removeQuestions(int index) {
      if (questionsBuilder_ == null) {
        ensureQuestionsIsMutable();
        questions_.remove(index);
        onChanged();
      } else {
        questionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion questions = 12;</code>
     */
    public grpc.GameManagementQuestion.Builder getQuestionsBuilder(
        int index) {
      return getQuestionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion questions = 12;</code>
     */
    public grpc.GameManagementQuestionOrBuilder getQuestionsOrBuilder(
        int index) {
      if (questionsBuilder_ == null) {
        return questions_.get(index);  } else {
        return questionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion questions = 12;</code>
     */
    public java.util.List<? extends grpc.GameManagementQuestionOrBuilder> 
         getQuestionsOrBuilderList() {
      if (questionsBuilder_ != null) {
        return questionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(questions_);
      }
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion questions = 12;</code>
     */
    public grpc.GameManagementQuestion.Builder addQuestionsBuilder() {
      return getQuestionsFieldBuilder().addBuilder(
          grpc.GameManagementQuestion.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion questions = 12;</code>
     */
    public grpc.GameManagementQuestion.Builder addQuestionsBuilder(
        int index) {
      return getQuestionsFieldBuilder().addBuilder(
          index, grpc.GameManagementQuestion.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc.GameManagementQuestion questions = 12;</code>
     */
    public java.util.List<grpc.GameManagementQuestion.Builder> 
         getQuestionsBuilderList() {
      return getQuestionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        grpc.GameManagementQuestion, grpc.GameManagementQuestion.Builder, grpc.GameManagementQuestionOrBuilder> 
        getQuestionsFieldBuilder() {
      if (questionsBuilder_ == null) {
        questionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            grpc.GameManagementQuestion, grpc.GameManagementQuestion.Builder, grpc.GameManagementQuestionOrBuilder>(
                questions_,
                ((bitField0_ & 0x00000800) != 0),
                getParentForChildren(),
                isClean());
        questions_ = null;
      }
      return questionsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:grpc.GameManagementGetResponse)
  }

  // @@protoc_insertion_point(class_scope:grpc.GameManagementGetResponse)
  private static final grpc.GameManagementGetResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.GameManagementGetResponse();
  }

  public static grpc.GameManagementGetResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GameManagementGetResponse>
      PARSER = new com.google.protobuf.AbstractParser<GameManagementGetResponse>() {
    @java.lang.Override
    public GameManagementGetResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GameManagementGetResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GameManagementGetResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.GameManagementGetResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

