// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.27.2

package grpc;

public interface GameManagementQuestionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.GameManagementQuestion)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>repeated string options = 2;</code>
   * @return A list containing the options.
   */
  java.util.List<java.lang.String>
      getOptionsList();
  /**
   * <code>repeated string options = 2;</code>
   * @return The count of options.
   */
  int getOptionsCount();
  /**
   * <code>repeated string options = 2;</code>
   * @param index The index of the element to return.
   * @return The options at the given index.
   */
  java.lang.String getOptions(int index);
  /**
   * <code>repeated string options = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the options at the given index.
   */
  com.google.protobuf.ByteString
      getOptionsBytes(int index);

  /**
   * <code>int32 correctAnswer = 3;</code>
   * @return The correctAnswer.
   */
  int getCorrectAnswer();

  /**
   * <code>int32 timeLimit = 4;</code>
   * @return The timeLimit.
   */
  int getTimeLimit();
}
