// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.27.2

package grpc;

public interface GameManagementResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.GameManagementResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool finished = 1;</code>
   * @return The finished.
   */
  boolean getFinished();
}
