// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.27.2

package grpc;

public interface GameManagementQuizQuestionsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.GameManagementQuizQuestionsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string gameId = 1;</code>
   * @return The gameId.
   */
  java.lang.String getGameId();
  /**
   * <code>string gameId = 1;</code>
   * @return The bytes for gameId.
   */
  com.google.protobuf.ByteString
      getGameIdBytes();
}
