// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.27.2

package grpc;

public final class Service {
  private Service() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Service.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_GameManagement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_GameManagement_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_GameManagementInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_GameManagementInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_GameManagementStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_GameManagementStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_GameManagementResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_GameManagementResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\022\004grpc\"\203\001\n\016GameManagement" +
      "\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\r\n\005image\030\003 \001(" +
      "\t\022\014\n\004type\030\004 \001(\t\022\030\n\020allowedItemTrade\030\005 \001(" +
      "\010\022\020\n\010tutorial\030\006 \001(\t\022\016\n\006status\030\007 \001(\005\"~\n\031G" +
      "ameManagementInfoRequest\022\n\n\002id\030\001 \001(\t\022\014\n\004" +
      "name\030\002 \001(\t\022\r\n\005image\030\003 \001(\t\022\014\n\004type\030\004 \001(\t\022" +
      "\030\n\020allowedItemTrade\030\005 \001(\010\022\020\n\010tutorial\030\006 " +
      "\001(\t\"9\n\033GameManagementStatusRequest\022\n\n\002id" +
      "\030\001 \001(\t\022\016\n\006status\030\002 \001(\005\";\n\026GameManagement" +
      "Response\022\020\n\010finished\030\001 \001(\010\022\017\n\007message\030\002 " +
      "\001(\t2\265\001\n\025GameManagementService\022K\n\nupdateI" +
      "nfo\022\037.grpc.GameManagementInfoRequest\032\034.g" +
      "rpc.GameManagementResponse\022O\n\014updateStat" +
      "us\022!.grpc.GameManagementStatusRequest\032\034." +
      "grpc.GameManagementResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpc_GameManagement_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_GameManagement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_GameManagement_descriptor,
        new java.lang.String[] { "Id", "Name", "Image", "Type", "AllowedItemTrade", "Tutorial", "Status", });
    internal_static_grpc_GameManagementInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_GameManagementInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_GameManagementInfoRequest_descriptor,
        new java.lang.String[] { "Id", "Name", "Image", "Type", "AllowedItemTrade", "Tutorial", });
    internal_static_grpc_GameManagementStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_grpc_GameManagementStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_GameManagementStatusRequest_descriptor,
        new java.lang.String[] { "Id", "Status", });
    internal_static_grpc_GameManagementResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_grpc_GameManagementResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_GameManagementResponse_descriptor,
        new java.lang.String[] { "Finished", "Message", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
